### Numpy Array

In [1]:
a = [1,2,3]

### Import numpy

In [2]:
import numpy as np

In [3]:
c = np.array([1,2,3])

In [4]:
c

array([1, 2, 3])

### one dimensional array

In [5]:
c[1]

2

In [6]:
array_1 = np.array([1,2,3,4,5,6,7,8])

In [7]:
array_1[3:]

array([4, 5, 6, 7, 8])

In [8]:
array_1.shape

(8,)

### 2 dimensional array consists of list of lists 

In [9]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
array_2 = np.array(list_of_lists)
array_2
print(array_2.shape)

(3, 3)


In [10]:
list_of_lists_2 =[[1,2],[3,4],[5,6]]
array_3 = np.array(list_of_lists_2)
print(array_3.shape)
array_3

(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

### Creating array

In [11]:
# np.zeros
print(np.zeros(8)) #1D
print(np.zeros([3,2])) #2D

[0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
# np.ones
print(np.ones(4))
print(np.ones([4,2]))

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
# np.empty
np.empty(5)
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
# np.arange
print(np.arange(10))
print(np.arange(0,10,2)) #(start,stop,step)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [15]:

np.arange(0,30,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [16]:
c = np.array([1,2,3,4,3,2,1,5,6,7,8,9])

#append
print(np.append(c,[10,11]))
#delete
print(np.delete(c,2))
#sort
print(np.sort(c))

[ 1  2  3  4  3  2  1  5  6  7  8  9 10 11]
[1 2 4 3 2 1 5 6 7 8 9]
[1 1 2 2 3 3 4 5 6 7 8 9]


In [17]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
array_3 = np.array([[1,2,3,4]])
array_4 = np.array([[5,6,7,8]])
np.vstack([array_3,array_4])
print(np.hstack([array_3,array_4]))

[[1 2 3 4 5 6 7 8]]


In [19]:
#np.expand_dims
array_7 = np.array([3,4,5,6,7,8,9])
array_8 = np.expand_dims(array_7,axis=1)
array_9 = np.expand_dims(array_7,axis=0)
print(array_8)
print(array_8.shape)
print(array_9)
print(array_9.shape)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(7, 1)
[[3 4 5 6 7 8 9]]
(1, 7)


### Operasi Matematika pada array sifatnya broadcast

In [20]:
array_7 = np.array([3,4,5,6,7,8,9])
array_7*2

array([ 6,  8, 10, 12, 14, 16, 18])

In [21]:
array_10 = np.array([[1,2,3],[4,5,6]])
array_10-4

array([[-3, -2, -1],
       [ 0,  1,  2]])

### Filtering Array 

In [22]:
array_7 = np.array([3,4,5,6,7,8,9])
print(array_7[array_7>5])
print(array_7[array_7==8])
print(array_7[array_7<=4])

[6 7 8 9]
[8]
[3 4]


In [23]:
array_11 = np.array([[3,5,7],[8,9,10],[-1,-2,-3]])
array_11.shape
print(array_11[array_11>5])

[ 7  8  9 10]


### hstack, vstack, hsplit, vsplit

In [24]:
#stack
array_14 = np.array([3,4,5,6,7])
array_15 = np.array([7,8,9,10,11])
print('Stack secara Vertikal')
print(np.vstack([array_14,array_15]))
print('Stack secara Horizontal')
print(np.hstack([array_14,array_15]))

Stack secara Vertikal
[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
Stack secara Horizontal
[ 3  4  5  6  7  7  8  9 10 11]


In [25]:
#hsplit
array_16 = np.array([3,4,5,6,7,8])
array_split = np.hsplit(array_16,2)
(array_split)

[array([3, 4, 5]), array([6, 7, 8])]

In [26]:
#vsplit
array_19 = np.array([[1,2,3,4],[4,5,6,7]])
print(array_19.shape)
print('Horizontal Split')
print(np.hsplit(array_19,2))
print('Vertical Split')
print(np.vsplit(array_19,2))

(2, 4)
Horizontal Split
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]])]
Vertical Split
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 7]])]


In [27]:
#vsplit
array_19 = np.array([[1,2,3,4,5,6],[4,5,6,7,5,6]])
print(array_19.shape)
print('Horizontal Split')
print(np.hsplit(array_19,3))
print('Vertical Split')
print(np.vsplit(array_19,3))

(2, 6)
Horizontal Split
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]]), array([[5, 6],
       [5, 6]])]
Vertical Split


ValueError: array split does not result in an equal division

### Operasi Aritmetik antar 2 array

In [28]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
print(array_a+array_b)

[4 6 8]


In [29]:
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_c-array_d)

[[-5 -5 -5]
 [-5 -5 -5]]


In [30]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_a.sum())
print(array_c.sum())
print(array_c.sum(axis=0))

6
21
[5 7 9]


### Transposing 

In [31]:
array_c = np.array([[5,2,3],[4,5,6]])
print(array_c)
print(array_c.shape)

[[5 2 3]
 [4 5 6]]
(2, 3)


In [32]:
array_d = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(array_d)
print(array_d.shape)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]
(3, 5)


In [33]:
array_d = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(array_d.T)
print(array_d.T.shape)

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]
 [ 5  8 11]]
(5, 3)


In [34]:
array_random = np.random.random([3,2])*100
print(array_random)

[[15.00335215 40.21344156]
 [52.01496651 68.19213027]
 [ 5.61430043  6.27025823]]


### Numpy Math formulas

In [35]:
array_random = np.random.random([3,2])*100
print(array_random)
np.sum(array_random)

[[92.57054922 58.60220171]
 [64.10153522 65.23007488]
 [28.56968721 36.73264766]]


345.8066958921387

In [36]:
np.square(9)

81

In [37]:
np.sqrt(9)

3.0

In [38]:
a = np.log(1000000)
print(a)

13.815510557964274


In [39]:
np.exp(a)

999999.9999999995

### Prime Number Generator Based on Interval

In [40]:

print('saadfs \n fdf')

saadfs 
 fdf


In [41]:
for i in range(5):
    print(i)

0
1
2
3
4


In [42]:
import numpy as np
a = np.array([3,2,1])

In [43]:
a[0]

3

In [44]:
np.empty((2,2))

array([[0.e+000, 1.e-323],
       [2.e-323, 3.e-323]])

In [45]:
np.arange(0,7,2)

array([0, 2, 4, 6])

### Bilangan prima adalah bilangan yang hanya bisa dibagi 1 dan dirinya sendiri

In [46]:
lower_limit = int(input('Lower Limit :'))
upper_limit = int(input("Upper Limit :"))
print(lower_limit, 'sampai',upper_limit)
for num in range(lower_limit,upper_limit+1):
    if num > 1:
        for i in range(2,num):#Filtering buat bilangan prima
            if (num%i)==0:
                break 
        else:
            print(num) #untuk kita dapat bilangan prima kondisi (num%i)==0 harus dilanggar

Lower Limit :4
Upper Limit :6
4 sampai 6
5


In [47]:
7%2

1